// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkspaceReservas.Models.Context;

#nullable disable

namespace WorkspaceReservas.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    [Migration("20260912232307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkspaceReservas.Models.Reserva", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fin");

                    b.Property<int>("IdSalaFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_sala_fk");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome_cliente");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.Property<bool>("status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("WorkspaceReservas.Models.Sala", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoPorHora")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_por_hora");

                    b.HasKey("Id");

                    b.ToTable("sala");
                });
#pragma warning restore 612, 618
        }
    }
}
