// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkspaceReservas.Models.Context;

#nullable disable

namespace WorkspaceReservas.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    [Migration("20260922171506_AddForeignKeyMedicoConsultas")]
    partial class AddForeignKeyMedicoConsultas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkspaceReservas.Models.Consulta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<long>("MedicoIdFk")
                        .HasColumnType("bigint")
                        .HasColumnName("id_medico_fk");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_paciente");

                    b.HasKey("Id");

                    b.HasIndex("MedicoIdFk");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("WorkspaceReservas.Models.Medico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crm");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("especialidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("WorkspaceReservas.Models.Reserva", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fin");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("inicio");

                    b.Property<int>("IdSalaFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_sala_fk");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome_cliente");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.Property<bool>("status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("WorkspaceReservas.Models.Sala", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoPorHora")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_por_hora");

                    b.HasKey("Id");

                    b.ToTable("sala");
                });

            modelBuilder.Entity("WorkspaceReservas.Models.Consulta", b =>
                {
                    b.HasOne("WorkspaceReservas.Models.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("WorkspaceReservas.Models.Medico", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
