@WorkspaceReservas_HostAddress = http://localhost:5189

GET {{WorkspaceReservas_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WorkspaceReservas_HostAddress}}/api/sala
Content-Type: application/json

{
  "Nome": "Sala 1 - teste",
  "Capacidade": 50,
  "PrecoPorHora": 100.00,
  "Ativo": true
}

###

PATCH {{WorkspaceReservas_HostAddress}}/api/sala
Content-Type: application/json

{
  "Id": 1,
  "Nome": "Sala 1 - teste atualizada",
  "Capacidade": 60,
  "PrecoPorHora": 120.00,
  "Ativo": true
}

###

GET {{WorkspaceReservas_HostAddress}}/api/sala/1

###

GET {{WorkspaceReservas_HostAddress}}/api/sala

###

DELETE {{WorkspaceReservas_HostAddress}}/api/sala/1

###
