@WorkspaceReservas_HostAddress = http://localhost:5189

GET {{WorkspaceReservas_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WorkspaceReservas_HostAddress}}/api/sala
Content-Type: application/json

{
  "Nome": "Sala 4 - teste",
  "Capacidade": -10,
  "PrecoPorHora": 100.00
}

###

PATCH {{WorkspaceReservas_HostAddress}}/api/sala
Content-Type: application/json

{
  "Id": 6,
  "ativo": false
}

###

GET {{WorkspaceReservas_HostAddress}}/api/sala/2

###

GET {{WorkspaceReservas_HostAddress}}/api/sala

###

DELETE {{WorkspaceReservas_HostAddress}}/api/sala/5

###

PUT {{WorkspaceReservas_HostAddress}}/api/sala/6/reativar

###

POST {{WorkspaceReservas_HostAddress}}/api/reserva
Content-Type: application/json

{
  "IdSalaFk": 2,
  "NomeCliente": "Teste",
  "DataHoraInicio": "2026-09-20T20:00:00",
  "DataHoraFim": "2026-09-20T20:01:00" 
}

###

GET {{WorkspaceReservas_HostAddress}}/api/reserva

###