@WorkspaceReservas_HostAddress = http://localhost:5189

GET {{WorkspaceReservas_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WorkspaceReservas_HostAddress}}/api/sala
Content-Type: application/json

{
  "Nome": "Sala 4 - teste",
  "Capacidade": -10,
  "PrecoPorHora": 100.00
}

###

PATCH {{WorkspaceReservas_HostAddress}}/api/sala
Content-Type: application/json

{
  "Id": 6,
  "ativo": false
}

###

GET {{WorkspaceReservas_HostAddress}}/api/sala/2

###

GET {{WorkspaceReservas_HostAddress}}/api/sala

###

DELETE {{WorkspaceReservas_HostAddress}}/api/sala/5

###

PUT {{WorkspaceReservas_HostAddress}}/api/sala/6/reativar

###

POST {{WorkspaceReservas_HostAddress}}/api/reserva
Content-Type: application/json

{
  "IdSalaFk": 2,
  "NomeCliente": "Teste",
  "DataHoraInicio": "2026-09-20T20:00:00",
  "DataHoraFim": "2026-09-20T20:01:00" 
}

### -- ROTAS DE RESERVAS

GET {{WorkspaceReservas_HostAddress}}/api/reserva

### --- FIM - ROTAS DE RESERVAS

### --- ROTAS DE MEDICOS

POST {{WorkspaceReservas_HostAddress}}/api/medicos
Content-type: application/json

{
  "Nome" :"Teste2",
  "CRM": "1234",
  "Especialidade": "ESPECIALIDADE - Teste"
}

###

PATCH {{WorkspaceReservas_HostAddress}}/api/medicos/1
Content-Type: application/json

{
  "Especialidade": "especialidade - Teste2"
}

### --- FIM - ROTAS DE MEDICOS


### --- ROTAS DE CONSULTAS

POST {{WorkspaceReservas_HostAddress}}/api/consultas
Content-Type: application/json

{  
  "MedicoIdFk": 2,
  "NomePaciente": "Teste2",
  "DataHoraInicio": "2026-09-23T20:00:00",
  "DataHoraFim": "2026-09-23T20:21:00" 
}

###

PATCH {{WorkspaceReservas_HostAddress}}/api/consultas/9
Content-Type: application/json

{  
  "MedicoIdFk": 2,
  "NomePaciente": "Teste"
}

###

DELETE {{WorkspaceReservas_HostAddress}}/api/consultas/3


###

GET {{WorkspaceReservas_HostAddress}}/api/consultas


###

GET {{WorkspaceReservas_HostAddress}}/api/consultas/3



